name: cl4ie-cpu
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - cpuonly
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - pyyaml>=5.4.0
  - tqdm>=4.62.0
  - opencv>=4.5.0
  - pip
  - pip:
    - transformers>=4.21.0
    - datasets>=2.4.0
    - evaluate>=0.2.0
    - layoutlm
    - pillow>=8.3.0
    - timm>=0.6.7
    - omegaconf>=2.2.0
    - hydra-core>=1.2.0
    - tensorboard>=2.7.0
    - neptune>=1.0.0
    - rich>=10.0.0
    - pytesseract>=0.3.8
    - pydantic>=1.8.0
    - seqeval>=1.2.2
    - pytest>=6.2.0
    - pytest-cov>=2.12.0
