experiment_name: "layoutlmv3_lwf_class_il"

dataset:
  name: "funsd"
  hf_dataset_name: "nielsr/funsd"
  task_type: "token_classification"
  preprocessing:
    max_seq_length: 512
    max_position_embeddings: 1024
    image_size: [224, 224]
    apply_ocr: false
    normalize_bbox: true
    include_image: false

model:
  name: "layoutlmv3"
  model_type: "layoutlmv3-base"
  pretrained_model_name: "microsoft/layoutlmv3-base"
  config:
    # Will be overridden to unified size by train_cl when label_space.unified is true
    num_labels: 51
    hidden_dropout_prob: 0.1
    attention_probs_dropout_prob: 0.1
    classifier_dropout: 0.1

cl_setting: "class_il"

training:
  batch_size: 1
  gradient_accumulation_steps: 4
  num_epochs: 1
  learning_rate: 5.0e-5
  weight_decay: 0.01
  warmup_ratio: 0.1
  optimizer: "adamw"
  scheduler: "linear"
  save_strategy: null
  evaluation_strategy: "epoch"
  save_total_limit: 1
  load_best_model_at_end: true
  metric_for_best_model: "f1"
  greater_is_better: true
  early_stopping_patience: 3

data_processing:
  train_split: "train"
  test_split: "test"
  validation_split: 0.1
  shuffle_train: true
  seed: 42

cl_strategy:
  name: "lwf"
  lwf_alpha: 0.5
  lwf_temperature: 2.0

label_space:
  unified: true

tasks:
  - name: "funsd"
    dataset:
      name: "funsd"
      hf_dataset_name: "nielsr/funsd"
  - name: "cord"
    dataset:
      name: "cord"
      hf_dataset_name: "naver-clova-ix/cord-v2"
  - name: "sroie"
    dataset:
      name: "sroie"
      hf_dataset_name: "buthaya/sroie"
  - name: "wildreceipt"
    dataset:
      name: "wildreceipt"
      hf_dataset_name: "kaydee/wildreceipt"
  - name: "xfund_zh"
    dataset:
      name: "xfund"
      hf_dataset_name: "nnul/xfund-multilingual"
      language: "zh"

evaluation:
  metrics: ["accuracy", "f1", "precision", "recall"]
  save_predictions: false

output:
  log_level: "INFO"
  save_model: true
  save_tokenizer: true
  push_to_hub: false

neptune:
  use_neptune: false
  neptune_project: "your-workspace/cl4ie"
  neptune_api_token: null
  tags: ["layoutlmv3", "class_il", "lwf", "unified", "funsd", "cord", "sroie", "wildreceipt", "xfund"]

