experiment_name: "layoutlm_sroie"

# Dataset configuration
dataset:
  name: "sroie"
  hf_dataset_name: "buthaya/sroie"
  task_type: "token_classification"
  preprocessing:
    max_seq_length: 512
    max_position_embeddings: 1024
    image_size: [224, 224]
    apply_ocr: false
    normalize_bbox: true
    include_image: true

# Model configuration  
model:
  name: "layoutlm"
  model_type: "layoutlm-base-uncased"
  pretrained_model_name: "microsoft/layoutlm-base-uncased"
  config:
    num_labels: 9  # 4 entity types (COMPANY, DATE, ADDRESS, TOTAL) with B-I tags + O
    hidden_dropout_prob: 0.1
    attention_probs_dropout_prob: 0.1
    classifier_dropout: 0.1

# Training configuration
training:
  batch_size: 16
  gradient_accumulation_steps: 1
  num_epochs: 50
  learning_rate: 5.e-5
  weight_decay: 0.01
  warmup_ratio: 0.1
  optimizer: "adamw"
  scheduler: "linear"
  save_strategy: "epoch"
  evaluation_strategy: "epoch"
  save_total_limit: 3
  load_best_model_at_end: true
  metric_for_best_model: "eval_f1"
  greater_is_better: true
  early_stopping_patience: 10

# Data processing
data_processing:
  train_split: "train"
  test_split: "test"
  validation_split: 0.1
  shuffle_train: true
  seed: 42

# Continual Learning Strategy
cl_strategy:
  name: "none"

# Evaluation settings
evaluation:
  metrics: ["accuracy", "f1", "precision", "recall"]
  save_predictions: true
  compute_entity_level_f1: true

# Logging and output
output:
  log_level: "INFO"
  save_model: true
  save_tokenizer: true
  push_to_hub: false
