"""Figures + table for thesis ch6 §6.6 (extended falsification results).

The falsification-ladder / CoLaR / capacity-gate numbers live in STATE.md and
``results/gates/`` (no ``.done`` markers), so they are NOT reachable through
``analyze_results.py``'s aggregation — they are pinned here as literals with their
source noted. The backbone-ordering figure reads live from ``results/all_runs.csv``.

Usage:
    uv run python scripts/build_falsification_figures.py
    uv run python scripts/ingest_to_thesis.py     # copy into thesis/
"""

from __future__ import annotations

from pathlib import Path

import matplotlib
import pandas as pd

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

OUT = Path("results")
BLUE, MUTED, ORANGE, AQUA = "#2a78d6", "#b9b8b2", "#eb6834", "#1baf7a"

plt.rcParams.update(
    {
        "font.size": 9,
        "axes.edgecolor": "#c9c9c5",
        "axes.linewidth": 0.7,
        "axes.grid": True,
        "grid.color": "#e8e8e4",
        "grid.linewidth": 0.5,
        "axes.axisbelow": True,
        "figure.facecolor": "white",
        "axes.facecolor": "white",
        "pdf.fonttype": 42,
    }
)

# STATE.md "GATE-0 FINAL" + carrier-diversity + data-hygiene blocks (dil, layer k=8).
LADDER = [
    ("Real whole-document activations (converged)", 87.3, True),
    ("Whole documents, matched 5-epoch budget", 63.8, True),
    ("Decoupled carriers (same features)", 36.7, False),
    ("Rank-16 spectral summary (SLR)", 41.9, False),
    ("Per-class Gaussians, full-$d$ (AGLR-CL)", 39.4, False),
    ("Real $k$-means centroids", 36.7, False),
]

# STATE.md CoLaR frontier block + replay_memory_bytes instrumentation.
PARETO = [
    ("Raw latent replay", 163, 87.3, False),
    ("CoLaR (per-doc SVD, $r{=}128$)", 60, 87.6, True),
    ("Spectral $r{=}16$", 0.45, 41.9, False),
    ("AGLR Gaussians", 0.39, 39.4, False),
    ("Coreset centroids", 0.48, 36.7, False),
]

# STATE.md 2026-08-14/15 NO-GO blocks (matched d5/r64 seed-42 gates).
GATES_TEX = r"""% Auto-generated by scripts/build_falsification_figures.py - CoLaSlot capacity gates.
% Matched DIL d5/r64 seed-42 gates; verdicts per STATE.md 2026-08-14/15 NO-GO records.
\begin{tabular}{llp{0.52\linewidth}}
\toprule
\textbf{Gate} & \textbf{Verdict} & \textbf{Decisive evidence} \\
\midrule
CoLaSlot-R & no-go & $+14.0$ AA over matched CoLaR but CORD $-0.84$ breaks the
$-0.5$ guardrail; test-blind calibration finds no usable abstention margin \\
CoLaSlot-RF & inert & dual slots-on/off evaluation exactly equal (AA $72.4$ both
ways); hard-label refit losses ${\sim}10^{-5}$ carry no drift signal \\
CoLaSlot-RA & harmful & acquisition-logit anchors train but cost $-0.43$ AA;
SROIE precision $-1.2$ from residual overgeneralization \\
\bottomrule
\end{tabular}
"""


def fig_ladder() -> None:
    fig, ax = plt.subplots(figsize=(5.6, 2.6), dpi=300)
    ys = range(len(LADDER))[::-1]
    ax.barh(
        list(ys),
        [v for _, v, _ in LADDER],
        height=0.6,
        color=[BLUE if hl else MUTED for _, _, hl in LADDER],
        zorder=3,
    )
    for y, (_, v, _) in zip(ys, LADDER, strict=True):
        ax.text(v + 1.2, y, f"{v:.1f}", va="center", fontsize=8.5, fontweight="bold")
    ax.set_yticks(list(ys))
    ax.set_yticklabels([n for n, _, _ in LADDER], fontsize=8.5)
    ax.set_xlim(0, 100)
    ax.set_xlabel("Average accuracy (entity-F1, DIL)")
    ax.grid(axis="y", visible=False)
    for s in ("top", "right", "left"):
        ax.spines[s].set_visible(False)
    fig.tight_layout()
    fig.savefig(OUT / "figure_falsification_ladder.pdf")
    plt.close(fig)


def fig_pareto() -> None:
    fig, ax = plt.subplots(figsize=(5.2, 2.8), dpi=300)
    for _, mb, aa, hl in PARETO:
        ax.scatter(
            mb, aa, s=70, color=BLUE if hl else MUTED, zorder=3, edgecolors="white", linewidths=1
        )
    offs = {
        "Raw latent replay": (9, -4, "left"),
        "CoLaR (per-doc SVD, $r{=}128$)": (-9, 3, "right"),
        "Spectral $r{=}16$": (9, 12, "left"),
        "AGLR Gaussians": (-9, -3, "right"),
        "Coreset centroids": (9, -19, "left"),
    }
    for name, mb, aa, hl in PARETO:
        dx, dy, ha = offs[name]
        ax.annotate(
            f"{name}\n{aa} AA · {mb:g} MB",
            (mb, aa),
            textcoords="offset points",
            xytext=(dx, dy),
            fontsize=7.5,
            ha=ha,
            fontweight="bold" if hl else "normal",
        )
    ax.set_xscale("log")
    ax.set_xlim(0.04, 900)
    ax.set_ylim(25, 100)
    ax.set_xlabel("Replay memory (MB, log scale)")
    ax.set_ylabel("AA (entity-F1, DIL)")
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)
    fig.tight_layout()
    fig.savefig(OUT / "figure_colar_pareto.pdf")
    plt.close(fig)


def fig_backbone() -> None:
    df = pd.read_csv(OUT / "all_runs.csv")
    df = df[df["scenario"] == "dil"]
    methods = ["naive", "ewc", "er", "der_pp", "er_cflat", "joint"]
    labels = ["Naive", "EWC", "ER", "DER++", "C-Flat++", "Joint"]
    fams = [
        ("layoutlmv3", "LayoutLMv3", BLUE),
        ("bert", "BERT (text-only)", ORANGE),
        ("lilt", "LiLT", AQUA),
    ]
    fig, ax = plt.subplots(figsize=(5.8, 2.7), dpi=300)
    w = 0.26
    for k, (fam, name, color) in enumerate(fams):
        sub = df[df["model_family"] == fam]
        # bert-naive rows are renamed to the bert_textonly comparator upstream.
        means = []
        for m in methods:
            key = "bert_textonly" if (fam == "bert" and m == "naive") else m
            vals = sub[sub["method"] == key]["AA"]
            means.append(vals.mean() if len(vals) else None)
        xs = [i + (k - 1) * w for i, v in enumerate(means) if v is not None]
        vs = [v for v in means if v is not None]
        ax.bar(xs, vs, width=w - 0.02, color=color, label=name, zorder=3)
        for x, v in zip(xs, vs, strict=True):
            ax.text(x, v + 1.5, f"{v:.0f}", ha="center", fontsize=6.5)
    ax.set_xticks(range(len(labels)))
    ax.set_xticklabels(labels, fontsize=8.5)
    ax.set_ylim(0, 100)
    ax.set_ylabel("AA (entity-F1, DIL)")
    ax.grid(axis="x", visible=False)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)
    ax.legend(loc="upper left", frameon=False, fontsize=7.5)
    fig.tight_layout()
    fig.savefig(OUT / "figure_backbone_ordering.pdf")
    plt.close(fig)


def main() -> None:
    fig_ladder()
    fig_pareto()
    fig_backbone()
    (OUT / "table_capacity_gates.tex").write_text(GATES_TEX)
    for f in (
        "figure_falsification_ladder.pdf",
        "figure_colar_pareto.pdf",
        "figure_backbone_ordering.pdf",
        "table_capacity_gates.tex",
    ):
        print(f"Wrote results/{f}")


if __name__ == "__main__":
    main()
