"""Adjudicate the image-CL scope test against docs/IMAGE_SCOPE_PREREG.md (+ Amendment 1).

Reads results/<scenario>_<method>_seed<S>_vit/metrics.json directly (no .done needed) and
prints/writes a verdict table. Rules are the pre-registered ones; nothing here is tuned.

    uv run python scripts/image_scope_verdict.py [--out docs/IMAGE_SCOPE_VERDICT.md]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

SEEDS = (42, 7, 123)
SCENARIOS = ("cil_cifar100", "cil_imagenet_r")
METHODS = (
    "naive",
    "joint",
    "ewc",
    "lwf",
    "er",
    "er_b2000",
    "der_pp",
    "der_pp_b2000",
    "slca",
    "slca_noca",
    "slca_noca_pub",
    "latent_replay_d500",
    "aglr_replay_keep100",
)
PUBLISHED = {  # SLCA Table 1, ViT-B/16 IN-21k (context only; gate is internal)
    "cil_cifar100": {"joint": 93.22, "slca": 91.53, "seq_ft": 88.86},
    "cil_imagenet_r": {"joint": 79.60, "slca": 77.00, "seq_ft": 71.80},
}


def load(results: Path) -> dict[tuple[str, str], dict[int, dict]]:
    out: dict[tuple[str, str], dict[int, dict]] = {}
    for sc in SCENARIOS:
        for me in METHODS:
            for sd in SEEDS:
                suffix = {"latent_replay_d500": "_d500", "aglr_replay_keep100": "_keep100"}.get(
                    me, ""
                )
                base = me.replace("_d500", "").replace("_keep100", "")
                p = results / f"{sc}_{base}_seed{sd}_vit{suffix}" / "metrics.json"
                if p.exists():
                    out.setdefault((sc, me), {})[sd] = json.loads(p.read_text())
    return out


def aa(runs: dict[tuple[str, str], dict[int, dict]], sc: str, me: str) -> dict[int, float]:
    return {sd: float(d["AA"]) for sd, d in runs.get((sc, me), {}).items()}


def paired(a: dict[int, float], b: dict[int, float]) -> tuple[list[float], list[int]]:
    seeds = sorted(set(a) & set(b))
    return [a[s] - b[s] for s in seeds], seeds


def rule_all_seeds(diffs: list[float], thresh: float, sign: int = 1) -> str:
    """Pre-registered: sign agrees on all 3 seeds and |mean| > pooled s.d.; thresh on mean."""
    if len(diffs) < 3:
        return f"INCOMPLETE ({len(diffs)}/3 seeds)"
    d = np.asarray(diffs) * sign
    ok = bool((d > 0).all() and abs(d.mean()) > d.std(ddof=1) and d.mean() >= thresh)
    return "SUPPORTED" if ok else "NOT SUPPORTED"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", type=Path, default=Path("results"))
    ap.add_argument("--out", type=Path, default=None)
    args = ap.parse_args()
    runs = load(args.results)
    lines = [
        "# Image-CL scope test — verdict (auto-generated by scripts/image_scope_verdict.py)",
        "",
    ]

    lines += [
        "## Cells (AA, mean ± sd over available seeds)",
        "",
        "| scenario | " + " | ".join(METHODS) + " |",
        "|---|" + "---|" * len(METHODS),
    ]
    for sc in SCENARIOS:
        row = []
        for me in METHODS:
            v = list(aa(runs, sc, me).values())
            row.append(
                f"{np.mean(v):.1f}±{np.std(v, ddof=1) if len(v) > 1 else 0:.1f} (n={len(v)})"
                if v
                else "—"
            )
        lines.append(f"| {sc} | " + " | ".join(row) + " |")
    lines += [
        "",
        "Published context (SLCA Tab. 1): "
        + "; ".join(
            f"{sc}: joint {p['joint']}, SLCA {p['slca']}, Seq-FT {p['seq_ft']}"
            for sc, p in PUBLISHED.items()
        ),
        "",
    ]

    lines += ["## Gate (internal, Amendment 1)", ""]
    for sc in SCENARIOS:
        j, n = aa(runs, sc, "joint").get(42), aa(runs, sc, "naive").get(42)
        # Amendment 3: joint within 10 pp of the published joint, naive < 25 (CIFAR: >83.2;
        # ImageNet-R: >69.6). Amendment 1's literal ">85" was written for CIFAR-100 only.
        j_min = PUBLISHED[sc]["joint"] - 10
        status = "n/a" if j is None or n is None else ("PASS" if j > j_min and n < 25 else "FAIL")
        lines.append(
            f"- {sc}: joint@42 = {j:.2f}, naive@42 = {n:.2f} (joint > {j_min:.1f}) → {status}"
            if status != "n/a"
            else f"- {sc}: n/a"
        )
    lines.append("")

    lines += ["## Hypotheses", ""]
    for sc in SCENARIOS:
        # H2: SLCA within 3 pp of joint AND within 3 pp of ER (2000-exemplar arm)
        slca, joint, er = aa(runs, sc, "slca"), aa(runs, sc, "joint"), aa(runs, sc, "er_b2000")
        dj, _ = paired(slca, joint)
        de, _ = paired(slca, er)
        if len(dj) == 3 and len(de) == 3:
            h2 = (
                "SUPPORTED"
                if (np.mean(dj) >= -3 and np.mean(de) >= -3)
                else ("KILLED" if np.mean(de) <= -10 else "NOT SUPPORTED")
            )
        else:
            h2 = f"INCOMPLETE (slca {len(slca)}, joint {len(joint)}, er_b2000 {len(er)})"
        lines.append(
            f"- **H2 [{sc}]** SLCA−joint = {np.mean(dj) if dj else float('nan'):.2f}, SLCA−ER2000 = {np.mean(de) if de else float('nan'):.2f} → {h2}"
        )
    # H2b on CIFAR-100
    sc = "cil_cifar100"
    naive, joint, noca = aa(runs, sc, "naive"), aa(runs, sc, "joint"), aa(runs, sc, "slca_noca")
    seeds = sorted(set(naive) & set(joint) & set(noca))
    if len(seeds) == 3:
        frac = [(noca[s] - naive[s]) / max(joint[s] - naive[s], 1e-6) for s in seeds]
        h2b = "SUPPORTED" if all(f >= 0.8 for f in frac) else "NOT SUPPORTED"
        lines.append(
            f"- **H2b** slow-trunk recovers {np.mean(frac)*100:.0f}% of the naive→joint gap (per seed {['%.2f' % f for f in frac]}) → {h2b}"
        )
    else:
        lines.append(f"- **H2b** INCOMPLETE ({len(seeds)}/3 seeds with naive+joint+slca_noca)")
    # H3: Gaussian summary within 3 pp of the real CLS bank — only meaningful if the bank works.
    bank, gauss = aa(runs, sc, "latent_replay_d500"), aa(runs, sc, "aglr_replay_keep100")
    dg, _ = paired(gauss, bank)
    if len(dg) == 3:
        floor = np.mean(list(naive.values())) + 10 if naive else 25
        if np.mean(list(bank.values())) < floor:
            h3 = f"INCONCLUSIVE (real bank {np.mean(list(bank.values())):.1f} is at the naive floor; pair cannot discriminate)"
        else:
            h3 = (
                "SUPPORTED"
                if np.mean(dg) >= -3
                else ("KILLED" if np.mean(dg) <= -10 else "NOT SUPPORTED")
            )
        lines.append(f"- **H3** Gaussian−bank = {np.mean(dg):.2f} → {h3}")
    else:
        lines.append(f"- **H3** INCOMPLETE (bank {len(bank)}, gaussian {len(gauss)})")
    lines += [
        "- **H1** (pilot displacement/CKA): results/pilot/cv_vit_{fast,slow}_seed*.json — head share of displacement 97-100% on 3/3 seeds, CKA monotone in depth → SUPPORTED (see docs/RESULTS_REPORT_2026-10.md §3.2).",
        "",
    ]

    text = "\n".join(lines)
    print(text)
    if args.out:
        args.out.write_text(text + "\n")


if __name__ == "__main__":
    main()
