#!/usr/bin/env bash
# Invalidate the results produced by the now-fixed baseline bugs so the grid re-runs
# them (the .done markers look valid but were generated by buggy code — see
# BUGFIX_REPORT.md). Removes the .done for o_lora / cl_lora / der_pp across the core
# scenarios both LOCALLY *and IN R2* — the latter is essential because the grid's
# sync_pull downloads R2's .done at launch, so a local-only removal would be undone by
# the pull and the grid would wrongly SKIP the bug re-runs.
#
# Set R2 creds in the env (R2_ACCESS_KEY_ID / R2_SECRET_ACCESS_KEY / R2_ENDPOINT,
# optional R2_BUCKET=doccl-results) to also purge R2; without them it is local-only.
# DRY_RUN=1 prints what would be removed without touching anything.
set -uo pipefail
cd "$(dirname "$0")/.."

METHODS="${METHODS:-o_lora cl_lora der_pp}"
SCENARIOS="${SCENARIOS:-cil_cord dil mixed}"
SEEDS="${SEEDS:-42 123 7}"
DRY_RUN="${DRY_RUN:-0}"

# ── Optional R2 remote (same construction as the grid's sync) ────────────────────
R2_BUCKET="${R2_BUCKET:-doccl-results}"
R2_ON=0
if [ -n "${R2_ACCESS_KEY_ID:-}" ] && [ -n "${R2_SECRET_ACCESS_KEY:-}" ] && [ -n "${R2_ENDPOINT:-}" ]; then
  export RCLONE_CONFIG_OBJ_TYPE=s3 RCLONE_CONFIG_OBJ_PROVIDER=Cloudflare
  export RCLONE_CONFIG_OBJ_ACCESS_KEY_ID="${R2_ACCESS_KEY_ID}"
  export RCLONE_CONFIG_OBJ_SECRET_ACCESS_KEY="${R2_SECRET_ACCESS_KEY}"
  export RCLONE_CONFIG_OBJ_ENDPOINT="${R2_ENDPOINT}" RCLONE_CONFIG_OBJ_REGION=auto
  command -v rclone >/dev/null 2>&1 && R2_ON=1
fi
R2_BASE="obj:${R2_BUCKET}/results"

n=0
for m in $METHODS; do for sc in $SCENARIOS; do for s in $SEEDS; do
  run="${sc}_${m}_seed${s}"
  d="results/${run}"
  hit=0
  [ -f "$d/.done" ] && hit=1
  # also treat a run present only in R2 as a hit (fresh box has no local copy yet)
  if [ "$R2_ON" = "1" ] && [ "$hit" = "0" ]; then
    rclone lsf "$R2_BASE/${run}/" 2>/dev/null | grep -q '\.done' && hit=1
  fi
  [ "$hit" = "1" ] || continue
  n=$((n+1))
  if [ "$DRY_RUN" = "1" ]; then
    echo "[dry] would invalidate ${run} (local$([ "$R2_ON" = "1" ] && echo '+R2'))"
  else
    rm -f "$d/.done" 2>/dev/null
    if [ "$R2_ON" = "1" ]; then
      # Remove the whole stale run dir in R2 so the fresh run replaces it cleanly.
      rclone purge "$R2_BASE/${run}" >/dev/null 2>&1 \
        || rclone delete "$R2_BASE/${run}/.done" >/dev/null 2>&1 || true
    fi
    echo "[invalidated] ${run} (.done removed local$([ "$R2_ON" = "1" ] && echo '+R2') -> grid re-runs)"
  fi
done; done; done
echo "=== ${n} buggy run(s) $([ "$DRY_RUN" = "1" ] && echo 'would be' || echo 'were') invalidated"\
"(R2 purge: $([ "$R2_ON" = "1" ] && echo ON || echo OFF — set R2_* creds to enable)) ==="
[ "$DRY_RUN" = "1" ] || echo "Next: launch the grid; these will re-run with the fixed code."
