#!/usr/bin/env bash
# Invalidate the results produced by the now-fixed baseline bugs so the grid re-runs
# them (the .done markers look valid but were generated by buggy code — see
# BUGFIX_REPORT.md). Removes the LOCAL .done for o_lora / cl_lora / der_pp across the
# core scenarios; the grid then regenerates them on the next launch. R2 copies are
# overwritten when the fresh runs sync (the .done is the gate, and we remove it here).
#
# DRY_RUN=1 prints what would be removed without touching anything.
set -uo pipefail
cd "$(dirname "$0")/.."

METHODS="${METHODS:-o_lora cl_lora der_pp}"
SCENARIOS="${SCENARIOS:-cil_cord dil mixed}"
SEEDS="${SEEDS:-42 123 7}"
DRY_RUN="${DRY_RUN:-0}"

n=0
for m in $METHODS; do for sc in $SCENARIOS; do for s in $SEEDS; do
  d="results/${sc}_${m}_seed${s}"
  marker="$d/.done"
  if [ -f "$marker" ]; then
    n=$((n+1))
    if [ "$DRY_RUN" = "1" ]; then
      echo "[dry] would invalidate $d"
    else
      rm -f "$marker"
      echo "[invalidated] $d (.done removed -> grid will re-run)"
    fi
  fi
done; done; done
echo "=== ${n} buggy run(s) $([ "$DRY_RUN" = "1" ] && echo 'would be' || echo 'were') invalidated ==="
[ "$DRY_RUN" = "1" ] || echo "Next: launch the grid; these will re-run with the fixed code."
